#!/bin/bash
echo "Compiling the project"
echo "--------------------------------------"
make clean
make
echo ""
echo "Running the demonstration"
echo "--------------------------------------"
./polygons
echo "--------------------------------------"

